config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers:{
  sessions: "admins/sessions",
  password: "admins/password",
  registrations: "admins/registrations"
  }


  namespace :admins do
  get '' => 'homes#top', as: :root
  get '/about' => 'homes#about', as: 'about'
  get '/reservations/complete' => 'reservations#complete', as: 'complete_reservation'
  get '/reservations/:id/confirm' => 'reservations#confirm', as: 'reservation_confirm'
  post '/reservations/:id/confirm', controller: 'registrations', action:'confirm'
  resources :reservations, expect:[:create] do
    resources :contacts, only:[:index, :update, :show]
  end
  resources :reservations_all, only:[:index]
  get '/reservations_all/search' => 'reservations_all#search', as: 'reservations_all_search'

  end

  devise_for :customers
  root to: 'homes#top'
  get 'about' => 'homes#about'
  patch 'customers/out' => 'customers#out', as: 'out_customers'
  get 'customers/quit' => 'customers#quit', as: 'quit_customers'
  get 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customers'
  resources :customers, only:[:show, :edit, :update]
  get 'reservations/select' => 'reservations#select', as: 'reservations_select'
  post 'registrations/new', controller: 'registrations', action: 'new'
  get 'reservations/log' => 'reservations#log', as: 'log_reservations'
  post 'reservations/log', controller: 'reservations', action: 'log'
  get 'reservations/thank' => 'reservations#thank', as: 'thank_reservations'
  get 'reservations/search' => 'reservations#search', as:'reservations_search'
  resources :reservations, only:[:index, :show, :new, :create] do
    resources :contacts, only:[:index,:create]
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer, required: true
  belongs_to :admin
  has_many :contacts
  include ActiveModel::Validations
  validates :title, presence: true
  validates_with DatetimeValidator
end

app/controllers/admins/reservations_controller.rb
class Admins::ReservationsController < ApplicationController
    def index
        @reservations = Reservation.where(admin_id:current_admin.id)
        @reservations = Reservation.all.page(params[:page]).per(8)
    end

    def confirm
        @reservation = Reservation.find(params[:id])
    end

    def complete
    end

    def show
        @reservation = Reservation.find(params[:id])
        @customer = @reservation.customer
    end

    def edit
    end

    def update
    end

    def destroy
        @reservation = Reservation.find(params[:id])
        @reservation.destroy
        redirect_to admins_complete_reservation_path
    end

    private
     def reservation_params
        params.require(:reservation).permit(:id,:dated_on, :title, :staff, :name, :email, :password, :encrypted_password)
     end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_reservation, only: [:show]
  before_action :authenticate_customer!


  def index
    @reservations = current_customer.reservations.where(end_time: DateTime.now..Float::INFINITY).order("#{sort_column} #{sort_direction}").page(params[:page]).per(8)
  end

  def show
    @reservations = Reservation.find(params[:id])
    @contacts = Contact.where(reservation_id:@reservations)
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.customer_id = current_customer.id
    if @reservation.valid?
      @reservation.save
      ReservationMailer.complete_reservation(@reservation.customer,@reservation).deliver
      redirect_to thank_reservations_path
    else
      render "new"
    end
  end

  def select
    @reservation = Reservation.new
    @admins = Admin.all
    @hash = Hash.new {}
    @admins.each do |admin|
      @hash[admin.name] = admin.id
    end
  end

  def new
    @reservation = Reservation.new(reservation_params)
    @reservations = Reservation.where(end_time: DateTime.now..Float::INFINITY).where(admin_id:@reservation.admin_id)
    @admins = Admin.all
    @hash = Hash.new {}
    @admins.each do |admin|
      @hash[admin.name] = admin.id
    end
  end

  def log
    @reservation = Reservation.new(reservation_params)
    @reservation.customer_id = current_customer.id
    if @reservation.invalid?
      @reservations = Reservation.where(end_time: DateTime.now..Float::INFINITY).where(admin_id:@reservation.admin_id)
      @admins = Admin.all
      @hash = Hash.new {}
      @admins.each do |admin|
        @hash[admin.name] = admin.id
      end
      render :new
    else
    end
  end

  def thank
  end

  private
  def reservation_params
    params.require(:reservation).permit(:customer_id,:admin_id,:start_time, :end_time, :dated_on, :title, :name, :staff, :detail)
  end

  def set_reservation
      @r = Reservation.find(params[:id])
  end

  def sort_direction
  %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
  Reservation.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/admins/reservations/complete.html.erb
<p>削除が完了しました。</p>

<%= link_to "予約一覧に戻る", admins_reservations_path, class: 'btn btn-primary' %>

app/views/admins/reservations/confirm.html.erb
<p>予約削除を希望している人のリスト</p>
<p>削除しますがよろしいですか</p>

<%= link_to "戻る", admins_reservation_path, class:"btn btn-primary" %>
<%= link_to "削除する", admins_reservation_path(params[:id]), method: :delete, class:"btn btn-danger" %>

app/views/admins/reservations/index.html.erb
<h2>管理者予約管理</h2>
<p>担当者<%= current_admin.name %></p>

<table class = "table">
    <thead>
        <tr>
            <th>予約日</th>
            <th>タイトル</th>
            <th>顧客名</th></th>
            <th>受付日</th>
        </tr>
    </thead>

    <tbody>
        <% @reservations.each do |reservation| %>
        <tr>
            <td><%= reservation.start_time.strftime('%Y/%m/%d %H時%M分') %>~<%= reservation.end_time.strftime('%H時%M分') %></td>
            <td><%= link_to reservation.title, admins_reservation_path(reservation.id) %></td>
            <td><%= reservation.customer.name %></td>
            <td><%= reservation.created_at.strftime('%Y/%m/%d %H時%M分') %></td>
        </tr>
        <% end %>
    </tbody>
</table>
    <%= paginate @reservations %>

app/views/admins/reservations/show.html.erb
<h2>管理者予約詳細</h2>
<h3><%= @customer.name %>さんの予約詳細</h3>

<table class = "table">
    <tbody>
        <div>
            <tr>
                <td>会員ID</td>
                <td><%= @customer.id %></td>
            </tr>

        </div>

        <div>
            <tr>
                <td>氏名</td>
                <td><%= @customer.name %></td>
            </tr>
        </div>

        <div>
            <tr>
                <td>住所</td>
                <td><%= @customer.address %></td>
            </tr>
        </div>

        <div>
            <tr>
                <td>電話番号</td>
                <td><%= @customer.telephone_number %></td>
            </tr>
        </div>

        <div>
            <tr>
                <td>メールアドレス</td>
                <td><%= @customer.email %></td>
            </tr>
        </div>

        <div>
            <tr>
                <td>アポイント日時</td>
                <td><%= @reservation.start_time %></td>
            </tr>
        </div>

        <div>
            <tr>
                <td>タイトル</td>
                <td><%= @reservation.title %></td>
            </tr>
        </div>

        <div>
            <tr>
                <td>要望</td>
                <td></td>
            </tr>
        </div>
    </tbody>
</table>

<%= link_to "削除", admins_reservation_confirm_path(@reservation.id), class: 'btn btn-primary' %>

<%= link_to "問い合わせ", admins_reservation_contacts_path(@reservation.id), class: 'btn btn-primary' %>

<%= link_to "一覧へ", admins_reservations_path, class: 'btn btn-primary' %>