config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers:{
  sessions: "admins/sessions",
  password: "admins/password",
  registrations: "admins/registrations"
  }


  namespace :admins do
  get '' => 'homes#top', as: :root
  get '/about' => 'homes#about', as: 'about'
  get '/reservations/complete' => 'reservations#complete', as: 'complete_reservation'
  get '/reservations/:id/confirm' => 'reservations#confirm', as: 'reservation_confirm'
  post '/reservations/:id/confirm', controller: 'registrations', action:'confirm'
  resources :reservations, expect:[:create] do
    resources :contacts, only:[:index, :update, :show]
  end
  resources :reservations_all, only:[:index]
  get '/reservations_all/search' => 'reservations_all#search', as: 'reservations_all_search'

  end

  devise_for :customers
  root to: 'homes#top'
  get 'about' => 'homes#about'
  patch 'customers/out' => 'customers#out', as: 'out_customers'
  get 'customers/quit' => 'customers#quit', as: 'quit_customers'
  get 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customers'
  resources :customers, only:[:show, :edit, :update]
  get 'reservations/select' => 'reservations#select', as: 'reservations_select'
  post 'registrations/new', controller: 'registrations', action: 'new'
  get 'reservations/log' => 'reservations#log', as: 'log_reservations'
  post 'reservations/log', controller: 'reservations', action: 'log'
  get 'reservations/thank' => 'reservations#thank', as: 'thank_reservations'
  get 'reservations/search' => 'reservations#search', as:'reservations_search'
  resources :reservations, only:[:index, :show, :new, :create] do
    resources :contacts, only:[:index,:create]
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :reservation
end

app/controllers/admins/contacts_controller.rb
class Admins::ContactsController < ApplicationController
  def index
    @reservation = Reservation.find(params[:reservation_id])
    @contacts = Contact.where(reservation_id:params[:reservation_id])
  end

  def update
    @contact = Contact.find(params[:id])
    @contact.reservation_id = params[:reservation_id]
    @customer = Customer.find_by(id:@contact.reservation.customer_id)
    @contact.update(contact_params)
    ContactMailer.send_when_admin_reply(@customer, @contact).deliver
    redirect_to action: :index
  end

  def show
    @contact = Contact.find_by(id:params[:id])
  end

  private

  def contact_params
    params.require(:contact).permit(:reservation_id,:question,:answer)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @contact = Contact.new
  end

  def create
    @reservation = params[:reservation_id]
    @contact = Contact.new(contact_params)
    @contact.reservation_id = @reservation
    @contact.save!
    redirect_to reservation_path(@reservation)
  end

  private

  def contact_params
    params.require(:contact).permit(:reservation_id,:question,:answer)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/admins/contacts/index.html.erb
<h2>問い合わせ一覧</h2>
<% @contacts.each do |contact| %>
<div>
  <%= contact.question %>
<% if contact.answer.present? %>
<p><%= link_to contact.answer, admins_reservation_contact_path(params[:reservation_id],contact.id) %></p>
<% else %>
<p><%= link_to "返答する", admins_reservation_contact_path(params[:reservation_id],contact.id), class: 'btn btn-primary' %></p>

<p><%= link_to "一覧に戻る", admins_reservations_path, class: 'btn btn-primary' %> </p>
<% end %>
</div>
<% end %>

app/views/admins/contacts/show.html.erb
<h3>問い合わせ内容</h3>
<div>
  <p><%= @contact.question %></p>
</div>


<h3>問い合わせに対するお答え</h3>



<%= form_with model:@contact,url:admins_reservation_contact_path(params[:reservation_id]), local:true do |f| %>

<%= f.text_area :answer, size:"65x20" %>
<%= f.submit "送信する", class: 'btn btn-primary' %>
<% end %>


<%= link_to "問い合わせ一覧", admins_reservation_contacts_path(params[:reservation_id]), class: 'btn btn-primary' %>