config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers:{
  sessions: "admins/sessions",
  password: "admins/password",
  registrations: "admins/registrations"
  }


  namespace :admins do
  get '' => 'homes#top', as: :root
  get '/about' => 'homes#about', as: 'about'
  get '/reservations/complete' => 'reservations#complete', as: 'complete_reservation'
  get '/reservations/:id/confirm' => 'reservations#confirm', as: 'reservation_confirm'
  post '/reservations/:id/confirm', controller: 'registrations', action:'confirm'
  resources :reservations, expect:[:create] do
    resources :contacts, only:[:index, :update, :show]
  end
  resources :reservations_all, only:[:index]
  get '/reservations_all/search' => 'reservations_all#search', as: 'reservations_all_search'

  end

  devise_for :customers
  root to: 'homes#top'
  get 'about' => 'homes#about'
  patch 'customers/out' => 'customers#out', as: 'out_customers'
  get 'customers/quit' => 'customers#quit', as: 'quit_customers'
  get 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customers'
  resources :customers, only:[:show, :edit, :update]
  get 'reservations/select' => 'reservations#select', as: 'reservations_select'
  post 'registrations/new', controller: 'registrations', action: 'new'
  get 'reservations/log' => 'reservations#log', as: 'log_reservations'
  post 'reservations/log', controller: 'reservations', action: 'log'
  get 'reservations/thank' => 'reservations#thank', as: 'thank_reservations'
  get 'reservations/search' => 'reservations#search', as:'reservations_search'
  resources :reservations, only:[:index, :show, :new, :create] do
    resources :contacts, only:[:index,:create]
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer, required: true
  belongs_to :admin
  has_many :contacts
  include ActiveModel::Validations
  validates :title, presence: true
  validates_with DatetimeValidator
end

app/controllers/admins/reservations_controller.rb
class Admins::ReservationsController < ApplicationController
    def index
        @reservations = Reservation.where(admin_id:current_admin.id)
        @reservations = Reservation.all.page(params[:page]).per(8)
    end

    def confirm
        @reservation = Reservation.find(params[:id])
    end

    def complete
    end

    def show
        @reservation = Reservation.find(params[:id])
        @customer = @reservation.customer
    end

    def edit
    end

    def update
    end

    def destroy
        @reservation = Reservation.find(params[:id])
        @reservation.destroy
        redirect_to admins_complete_reservation_path
    end

    private
     def reservation_params
        params.require(:reservation).permit(:id,:dated_on, :title, :staff, :name, :email, :password, :encrypted_password)
     end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_reservation, only: [:show]
  before_action :authenticate_customer!


  def index
    @reservations = current_customer.reservations.where(end_time: DateTime.now..Float::INFINITY).order("#{sort_column} #{sort_direction}").page(params[:page]).per(8)
  end

  def show
    @reservations = Reservation.find(params[:id])
    @contacts = Contact.where(reservation_id:@reservations)
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.customer_id = current_customer.id
    if @reservation.valid?
      @reservation.save
      ReservationMailer.complete_reservation(@reservation.customer,@reservation).deliver
      redirect_to thank_reservations_path
    else
      render "new"
    end
  end

  def select
    @reservation = Reservation.new
    @admins = Admin.all
    @hash = Hash.new {}
    @admins.each do |admin|
      @hash[admin.name] = admin.id
    end
  end

  def new
    @reservation = Reservation.new(reservation_params)
    @reservations = Reservation.where(end_time: DateTime.now..Float::INFINITY).where(admin_id:@reservation.admin_id)
    @admins = Admin.all
    @hash = Hash.new {}
    @admins.each do |admin|
      @hash[admin.name] = admin.id
    end
  end

  def log
    @reservation = Reservation.new(reservation_params)
    @reservation.customer_id = current_customer.id
    if @reservation.invalid?
      @reservations = Reservation.where(end_time: DateTime.now..Float::INFINITY).where(admin_id:@reservation.admin_id)
      @admins = Admin.all
      @hash = Hash.new {}
      @admins.each do |admin|
        @hash[admin.name] = admin.id
      end
      render :new
    else
    end
  end

  def thank
  end

  private
  def reservation_params
    params.require(:reservation).permit(:customer_id,:admin_id,:start_time, :end_time, :dated_on, :title, :name, :staff, :detail)
  end

  def set_reservation
      @r = Reservation.find(params[:id])
  end

  def sort_direction
  %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
  Reservation.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/index.html.erb
<h2>予約一覧</h2>
<div class="float-right">
<%= form_with model:@reservation, url:reservations_path, method: :get, local: true do |f|%>

<%= f.label :sort, 'ソート' %>
<%= f.select :sort, [['受付日', 'created_at'],['予約日','start_time']] %>

<%= f.select :direction, [['昇順', 'asc'],['降順','desc']] %>

<%= f.submit '並び替える' %>
<% end %>
</div>
<table class = "table">
    <thead>
        <tr>
            <th>予約日</th>
            <th>タイトル</th>
            <th>担当者</th>
            <th>受付日</th>
        </tr>
    </thead>

    <tbody>
        <% @reservations.each do |reservation| %>
        <tr>
            <td><%= reservation.start_time.strftime('%Y/%m/%d %H時%M分') %>~<%= reservation.end_time.strftime('%H時%M分') %></td>
            <td><%= link_to reservation.title, reservation_path(reservation.id) %></td>
            <td><%= reservation.staff %></td>
            <td><%= reservation.created_at.strftime('%Y/%m/%d %H時%M分') %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= link_to "新規予約", reservations_select_path, class: 'btn btn-success' %>
<%= paginate @reservations %>

app/views/reservations/log.html.erb
<h2>予約情報の確認</h2>

<h3>カレンダーで選んだ日付</h3>
<%= @reservation.start_time.strftime('%Y/%m/%d') %>

<h3>開始時刻</h3>
<%= @reservation.start_time.strftime('%H時%M分') %>
<%= @reservation.end_time.strftime('%H時%M分') %>

<h3>タイトル</h3>
<%= @reservation.title %>

<h3>担当者</h3>
<%= @reservation.admin.name %>

<h3>ご要望</h3>
<%= @reservation.detail %>

<%= form_with model: @reservation, url:reservations_path, local: true do |f| %>
<%= f.hidden_field :title, :value => @reservation.title %>
<%= f.hidden_field :staff, :value => @reservation.admin.name %>
<%= f.hidden_field :start_time, :value => @reservation.start_time %>
<%= f.hidden_field :end_time, :value => @reservation.end_time %>
<%= f.hidden_field :admin_id, :value => @reservation.admin_id %>
<%= f.hidden_field :name, :value => current_customer.name %>
<%= f.hidden_field :detail, :value => @reservation.detail %>
<%= f.submit "確定",class: 'btn btn-primary' %>

<% end %>

app/views/reservations/new.html.erb
<h2>予約入力</h2>
<%= render 'layouts/error', reservation: @reservation %>

<%= week_calendar events: @reservations do |date, reservations|%>
  <div class="text-center">

      <% if date.wday == 0 || date.wday == 6 %>
      <p>X</p>
      <% end %>

    <% reservations.each do |reservation| %>
      <% if reservation.start_time.strftime("%H:%M") >= @t1.strftime("%H:%M") && reservation.start_time.strftime("%H:%M") < @t2.strftime("%H:%M") %>
        <% if reservation.customer_id == current_customer.id %>
          <%= link_to reservation.start_time.strftime("%H:%M")+"~"+reservation.end_time.strftime("%H:%M"), reservation %>
        <% else %>
          <h4>×</h4>
        <% end %>
      <% else %>

      <% end %>
    <% end %>
  </div>

<% end %>


<%= form_with model:@reservation, url:log_reservations_path,method: :post,  local: true do |f| %>
<div>
  <%= f.label :title, "タイトル" %>
  <%= f.text_field :title %>
</div>

<div>
 <p>担当者 <%= @reservation.admin.name %></p>
</div>

<div>
  <%= f.label :start_time,'開始時刻' %>
  <%= f.datetime_select :start_time, {minute_step: 15, start_hour: 9, end_hour:19} %>
</div>
<div>
  <%= f.label :end_time, '終了時刻'%>
  <%= f.datetime_select :end_time, {minute_step: 15, start_hour: 9, end_hour:19} %>
</div>
<div>
  <%= f.label :detail, 'ご要望'%>
  <%= f.text_area :detail %>
</div>
<div>
  <%= f.submit "予約確認へ", class: 'btn btn-primary' %>
</div>

<%= f.hidden_field :admin_id, :value => @reservation.admin_id %>

<% end %>

app/views/reservations/select.html.erb
<%= form_with model:@reservation, url:new_reservation_path,method: :get, local: true  do |f| %>

<div class="form-group justify-content-center">
  <%= f.label :admin_id, " 担当者" %>
  <%= f.select :admin_id, @hash, include_blank: "選択してください" ,class:"form-select"%>
</div>

<div>
  <%= f.submit "探す" %>
</div>

<% end %>

app/views/reservations/show.html.erb
<h2>予約詳細</h2>

<h3>日時</h3>
<%= @reservations.start_time.strftime('%Y/%m/%d') %>~<%= @reservations.end_time.strftime('%Y/%m/%d') %>

<h3>タイトル</h3>
<%= @reservations.title %>

<h3>担当者</h3>
<%= @reservations.staff %>

<h3>受付日</h3>
<%= @reservations.created_at.strftime('%H時%M分') %>

<h3>ご要望</h3>
<%= @reservations.detail %>

<div>
    <% if @contacts.present? %>
        <% @contacts.each do |contact| %>
            <p><%= contact.question %></p>
            <% if contact.answer.present? %>
            <p><%= contact.answer %></p>
            <% end %>
        <% end %>
    <% else %>
        <p>お問い合わせはありません</p>
    <% end %>
<p> <%= link_to "お問い合わせ", reservation_contacts_path(params[:id]), class: 'btn btn-primary' %></p>
</div>

<p> <%= link_to "予約一覧へ", reservations_path, class: 'btn btn-primary' %> </p>

app/views/reservations/thank.html.erb
<h2>ご予約ありがとうございました。</h2>

<%= link_to "一覧に戻る", reservations_path, class: 'btn btn-primary' %>