config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers:{
  sessions: "admins/sessions",
  password: "admins/password",
  registrations: "admins/registrations"
  }


  namespace :admins do
  get '' => 'homes#top', as: :root
  get '/about' => 'homes#about', as: 'about'
  get '/reservations/complete' => 'reservations#complete', as: 'complete_reservation'
  get '/reservations/:id/confirm' => 'reservations#confirm', as: 'reservation_confirm'
  post '/reservations/:id/confirm', controller: 'registrations', action:'confirm'
  resources :reservations, expect:[:create] do
    resources :contacts, only:[:index, :update, :show]
  end
  resources :reservations_all, only:[:index]
  get '/reservations_all/search' => 'reservations_all#search', as: 'reservations_all_search'

  end

  devise_for :customers
  root to: 'homes#top'
  get 'about' => 'homes#about'
  patch 'customers/out' => 'customers#out', as: 'out_customers'
  get 'customers/quit' => 'customers#quit', as: 'quit_customers'
  get 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customers'
  resources :customers, only:[:show, :edit, :update]
  get 'reservations/select' => 'reservations#select', as: 'reservations_select'
  post 'registrations/new', controller: 'registrations', action: 'new'
  get 'reservations/log' => 'reservations#log', as: 'log_reservations'
  post 'reservations/log', controller: 'reservations', action: 'log'
  get 'reservations/thank' => 'reservations#thank', as: 'thank_reservations'
  get 'reservations/search' => 'reservations#search', as:'reservations_search'
  resources :reservations, only:[:index, :show, :new, :create] do
    resources :contacts, only:[:index,:create]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reservation
  validates :name, :email, :encrypted_password, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :reservation
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reservations
  validates :name, :address, :email, :encrypted_password, presence: true
  validates :telephone_number, numericality: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer, required: true
  belongs_to :admin
  has_many :contacts
  include ActiveModel::Validations
  validates :title, presence: true
  validates_with DatetimeValidator
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  def top
    @admin = current_admin
    @reservations = @admin.reservation.all
  end

  def about
    @admin = current_admin
    @reservations = Reservation.where(staff:@admin.name)
  end

end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?


def after_sign_in_path_for(resource)
        case resource
        when Admin
            admins_about_path
        when Customer
            customer_path(:id)
        end
end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email,:address,:telephone_number,:password,:password_confirmation])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @contact = Contact.new
  end

  def create
    @reservation = params[:reservation_id]
    @contact = Contact.new(contact_params)
    @contact.reservation_id = @reservation
    @contact.save!
    redirect_to reservation_path(@reservation)
  end

  private

  def contact_params
    params.require(:contact).permit(:reservation_id,:question,:answer)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show
    @all_reservations = current_customer.reservations.all
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    @customer.update(customer_params)
    redirect_to customer_path(current_customer.id)
  end

  def quit
    @customer = Customer.find_by(params[:id])
  end

  def out
    @customer = current_customer
    @customer.update(is_active: true)
    reset_session
    redirect_to withdraw_customers_path
  end

  def withdraw
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :email, :encrypted_password, :address, :telephone_number, :is_active)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_reservation, only: [:show]
  before_action :authenticate_customer!


  def index
    @reservations = current_customer.reservations.where(end_time: DateTime.now..Float::INFINITY).order("#{sort_column} #{sort_direction}").page(params[:page]).per(8)
  end

  def show
    @reservations = Reservation.find(params[:id])
    @contacts = Contact.where(reservation_id:@reservations)
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.customer_id = current_customer.id
    if @reservation.valid?
      @reservation.save
      ReservationMailer.complete_reservation(@reservation.customer,@reservation).deliver
      redirect_to thank_reservations_path
    else
      render "new"
    end
  end

  def select
    @reservation = Reservation.new
    @admins = Admin.all
    @hash = Hash.new {}
    @admins.each do |admin|
      @hash[admin.name] = admin.id
    end
  end

  def new
    @reservation = Reservation.new(reservation_params)
    @reservations = Reservation.where(end_time: DateTime.now..Float::INFINITY).where(admin_id:@reservation.admin_id)
    @admins = Admin.all
    @hash = Hash.new {}
    @admins.each do |admin|
      @hash[admin.name] = admin.id
    end
  end

  def log
    @reservation = Reservation.new(reservation_params)
    @reservation.customer_id = current_customer.id
    if @reservation.invalid?
      @reservations = Reservation.where(end_time: DateTime.now..Float::INFINITY).where(admin_id:@reservation.admin_id)
      @admins = Admin.all
      @hash = Hash.new {}
      @admins.each do |admin|
        @hash[admin.name] = admin.id
      end
      render :new
    else
    end
  end

  def thank
  end

  private
  def reservation_params
    params.require(:reservation).permit(:customer_id,:admin_id,:start_time, :end_time, :dated_on, :title, :name, :staff, :detail)
  end

  def set_reservation
      @r = Reservation.find(params[:id])
  end

  def sort_direction
  %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
  Reservation.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end
end

app/helpers/admins/admins_helper.rb
module Admins::AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reservations_all_helper.rb
module ReservationsAllHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'btn btn-primary' %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'btn btn-primary' %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'btn btn-primary' %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: 'btn btn-primary' %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: 'btn btn-primary' %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: 'btn btn-primary' %><br />
  <% end %>
<% end %>

app/views/layouts/_admininfo.html.erb
<div class="row">
    <div class="col-lg-4">
      <table class = "table">
        <thead>
          <tr><th>氏名</th><td><%= current_admin.name %></td></tr>
          <tr><th>メールアドレス</th><td><%= current_admin.email %></td></tr>
        </thead>
      </table>

    <% @reservations = current_admin.reservation.where(start_time:Date.today.in_time_zone.all_day) %>
    <% if @reservations.present? %>
    <div>
      <p class="text-center">本日のご予約</p>
      <table class="table">
        <tr>
          <th >開始時刻</th>
          <th>タイトル</th>
        </tr>
          <% @reservations.each do |reservation| %>
          <tr>
            <td><%= reservation.start_time.strftime("%H時%M分") %></td>
            <td><%= reservation.title %></td>
          </tr>
          <% end %>
      </table>
    </div>
    <% else %>
    <p>今日の予約はありません</p>
    <% end %>
    </div>

app/views/layouts/_error.html.erb
<% if reservation.errors.any? %>
<div id="error_messages">
    <h3>予約に失敗しました</h3>
    <ul>
    <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
</div>
<% end %>

app/views/layouts/_userinfo.html.erb
<div class="row">
    <div class="col-lg-4">
    <table class = "table">
      <thead>
        <tr><th>氏名</th><td><%= current_customer.name %></td></tr>
        <tr><th>住所</th><td><%= current_customer.address %></td></tr>
        <tr><th>電話番号</th><td><%= current_customer.telephone_number %></td></tr>
        <tr><th>メールアドレス</th><td><%= current_customer.email %></td></tr>
      </thead>
    </table>
    <div class="mb-2">
    <%= link_to "退会はこちら", quit_customers_path(current_customer.id), class: 'btn btn-primary' %>
    <%= link_to "編集する", edit_customer_path(current_customer.id), class: 'btn btn-success' %>
    </div>
    <hr>

    <% @reservations = current_customer.reservations.where(start_time:Date.today.in_time_zone.all_day) %>
    <% if @reservations.present? %>
    <div>
      <p class="text-center">本日のご予約</p>
      <table class="table">
        <tr>
          <th >開始時刻</th>
          <th>タイトル</th>
        </tr>
          <% @reservations.each do |reservation| %>
          <tr>
            <td><%= reservation.start_time.strftime("%H時%M分") %></td>
            <td><%= reservation.title %></td>
          </tr>
          <% end %>
      </table>
    </div>
    <% else %>
    <p>本日の予約はありません</p>
    <% end %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary mt-0 mb-0 p-3">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'SCHEDULER', root_path,class:'navbar-brand' %>
    <div class="collapse navbar-collapse justify-content-end">
    <ul class="navbar-nav">
      <% if customer_signed_in? %>
        <li class="nav-item active">
          <%= link_to "マイページ", customer_path(current_customer),class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "予約一覧", reservations_path,class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%=  link_to "新規予約", reservations_select_path,class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class:'nav-link' %>
        </li>
      <% elsif admin_signed_in? %>

        <li class="nav-item active">
          <%= link_to "ホーム", admins_root_path,class:'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to "About", admins_about_path,class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "予約一覧",admins_reservations_path,class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "新規登録", new_customer_registration_path,class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_customer_session_path,class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "管理者ログイン", admin_session_path,class:'nav-link' %>
        </li>
      <% end %>
    </ul>
    </div>
    </nav>
    </header>
    <main>
    <%= yield %>
    </main>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <% if t('date.abbr_day_names')[day.wday] == "日" %>
          <th class="text-danger"><%= t('date.abbr_day_names')[day.wday] %></th>
          <% elsif t('date.abbr_day_names')[day.wday] == "土" %>
          <th class="text-primary"><%= t('date.abbr_day_names')[day.wday] %></th>
          <% else %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
          <% end %>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '前の週へ'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: '次の週へ'), calendar.url_for_next_view %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th></th>
        <% date_range.each_slice(7) do |week| %>
        <% date_range.slice(0, 7).zip(week).each do |day,date| %>
          <th><%= date.strftime("%m/%d") %>(<%= t('date.abbr_day_names')[day.wday] %>)</th>
        <% end %>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @repeat = Range.new(0,9) %>
      <% @t1 = Time.zone.parse("2000-01-01 09:00:00") %>
      <% @t2 = Time.zone.parse("2000-01-01 10:00:00") %>
      <% date_range.each_slice(7) do |week| %>
      <% @repeat.each do |time|%>
        <tr>
          <td>
            <%= @t1.strftime("%H:%M") %>~<%= @t2.strftime("%H:%M") %>
          </td>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>

              <% else %>

                <% passed_block.call day, sorted_events.fetch(day, []) %>

              <% end %>
            <% end %>
          <% end %>
           <% @t1 += 3600 %>
           <% @t2 += 3600 %>
          </tr>
          <% end %>
      <% end %>
    </tbody>
  </table>
</div>